YAN-46: Добавить Service Workers
xexex98/yandex-react-game pull request #24
Opened 2024-07-03 08:18 UTC by trishinanton

YAN-46: Добавить Service Workers

https://linear.app/yandex-react-game/issue/YAN-46/dobavit-service-workers

2024-07-03 08:24 UTC, alexxxpo submitted a review, later dismissed

2024-07-03 11:34 UTC, xexex98 approved these changes, later dismissed

2024-07-03 14:57 UTC, xexex98 submitted a review, later dismissed

2024-07-04 00:59 UTC, kyzinatra commented on packages/client/sw.js
> +                  // Записываем в кеш ответ, используя в качестве ключа запрос
Хорошее кэширование запросов. Единственное что стоит подумать о инвалидации кэша. Что если мы знаем, что комментарии на сервере обновились. Как дать понять, что нам нужен именно свежий запрос, а кэш нас не интересует

2024-07-04 01:01 UTC, kyzinatra commented on packages/client/sw.js
> +      })
Надо исправить: service worker не может кэшировать всю папку. Он не знает что там находиться. Для него необходимо указать все пути до всей статики и только тогда она будет закэширована. Для этого можно использовать специальные инструменты и библиотеки, которые либо в runtime либо при сборке подставляют все пути до статики

2024-07-04 01:02 UTC, kyzinatra requested changes
Отличная работа! Понравилась реализация кэширования fetch запрсов, единственно что, сейчас не работает кэширование статики при установке. Service worker не может кэшировать всю папку. Он не знает что там находиться. Для него необходимо указать все пути до всей статики и только тогда она будет закэширована. Для этого можно использовать специальные инструменты и библиотеки, которые либо в runtime либо при сборке подставляют все пути до статики

2024-07-05 00:10 UTC, kyzinatra approved these changes
Выглядит гораздо лучше! Ваша работа принята, желаю успехов в дальнейшем обучении

2024-07-05 07:25 UTC, xexex98 approved these changes

2024-07-05 11:12 UTC, alexxxpo approved these changes

2024-07-05 11:13 UTC, merged