YAN-50 тесты на игровой движок
xexex98/yandex-react-game pull request #32
Opened 2024-07-13 22:31 UTC by wwwriterrr

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-07-13 22:50 UTC, drun48 submitted a review, later dismissed

2024-07-14 07:08 UTC, xexex98 approved these changes, later dismissed

2024-07-14 08:31 UTC, kyzinatra requested changes
Сейчас неплохо организована структура тестов. Мне нравятся названия, но хотелось бы видеть сильно больше тестов самой игры. По сути сейчас больше тестируется testCircle и функции кнваса, а сама игра проверяется только not to be null. Стоит описать более полноценные тесты для игры, которые бы тестировали ее функции и возможности, специфичные для самой игры (какие-то функции самого движка игры). К сожалению на данном этапе по сути движок не тестируется, стоит поправить этот момент и отправить работу на проверку снова ^_^ 

UPD: Возможно стоит тестировать не сам компонент `Game` А хук, котороый он использует. Он больше похож на движок. Замокать функции и проверять, что он работает во всех сценариях корректно

2024-07-15 00:36 UTC, kyzinatra approved these changes
Да, тест выглядит гораздо лучше. Теперь он правда что-то тестирует. Конечно, хорошо бы развивать его и дальше, писать более обьемные тесты, которые охватывают больший спектр логики, но как минимальное начало - неплохо.

2024-07-15 07:22 UTC, trishinanton approved these changes

2024-07-15 16:41 UTC, xexex98 approved these changes

2024-07-15 16:42 UTC, merged