YAN-27:Настроить обработку ошибок внутри «детей» React-компонентов
xexex98/yandex-react-game pull request #5
Opened 2024-06-20 15:56 UTC by trishinanton

Настроить обработку ошибок внутри «детей» React-компонентов

https://linear.app/yandex-react-game/issue/YAN-27/nastroit-obrabotku-oshibok-vnutri-%C2%ABdetej%C2%BB-react-komponentov

2024-06-20 16:13 UTC, xexex98 approved these changes, later dismissed

2024-06-21 07:39 UTC, alexxxpo submitted a review, later dismissed

2024-06-21 07:43 UTC, holypower777 requested changes

2024-06-21 07:43 UTC, holypower777 commented on packages/client/src/pages/game/game.tsx
> +  return (
почему только страницу игры обернул?

2024-06-21 07:43 UTC, holypower777 commented on packages/client/src/components/ErrorBoundary/index.tsx
> +interface ErrorBoundaryProps {
тут лучше type использовать
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

type и для Props тоже стоит юзать, да и в целом всего, когда не надо расширять этот тип, в таких случаях interface

2024-06-21 07:43 UTC, holypower777 commented on packages/client/src/components/ErrorBoundary/index.tsx
> +  children: ReactNode
можно добавить ещё `ReactNode[]` или как-то заюзать `React.PropsWithChildren`

2024-06-21 14:32 UTC, trishinanton commented on packages/client/src/pages/game/game.tsx
> +  return (
да это как пример, пока непонятно, что именно будем оборачивать

2024-06-21 14:34 UTC, trishinanton commented on packages/client/src/components/ErrorBoundary/index.tsx
> +interface ErrorBoundaryProps {
хуливарный вопрос, тут как договориться, если всем удобнее на type, то могу на type переписать

2024-06-21 17:47 UTC, holypower777 commented on packages/client/src/pages/game/game.tsx
> +  return (
почему? всегда оборачивают главный компонент, App в нашем случае, чтоб белый экране ловить ни от одной страницы

2024-06-24 13:01 UTC, trishinanton commented on packages/client/src/components/ErrorBoundary/index.tsx
> +  children: ReactNode
под капотом PropsWithChildren определен так
  type PropsWithChildren<P = unknown> = P & { children?: ReactNode | undefined };
  
 тип ReactNode подразумевает под собой все возможные типы чилда
 
 type ReactNode = ReactElement | string | number | ReactFragment | ReactPortal | boolean | null | undefined;

2024-06-24 14:20 UTC, holypower777 approved these changes

2024-06-24 15:04 UTC, xexex98 commented on packages/client/src/routes.tsx
а тут есть смысл оборавчивать вск страницы в errorbiundary если мы глобальный уже обернули?

2024-06-24 20:44 UTC, trishinanton commented on packages/client/src/routes.tsx
роутер так не работает, если только сверху обернуть, надо обязтельно тут указать

2024-06-25 01:39 UTC, alexxxpo approved these changes

2024-06-25 06:52 UTC, merged