Feat/yan 28
xexex98/yandex-react-game pull request #6
Opened 2024-06-21 14:31 UTC by trishinanton

Создать механику игры на Canvas API

https://linear.app/yandex-react-game/issue/YAN-28/sozdat-mehaniku-igry-na-canvas-api

2024-06-21 15:30 UTC, holypower777 requested changes

2024-06-21 15:30 UTC, holypower777 commented on packages/client/src/components/ErrorBoundary/index.tsx
> +import { Component, ReactNode, ErrorInfo } from 'react'
этого тут быть не должно, ты видимо отбранчевался не от мейна, а от своей ветки, вмержи мейн себе плиз

2024-06-22 08:30 UTC, alexxxpo submitted a review, later dismissed

2024-06-24 13:22 UTC, trishinanton commented on packages/client/src/components/ErrorBoundary/index.tsx
> +import { Component, ReactNode, ErrorInfo } from 'react'
да, как пр с 27 таской вмержу и подолью изменения

2024-06-25 07:05 UTC, alexxxpo approved these changes, later dismissed

2024-06-25 10:19 UTC, kyzinatra commented on packages/client/src/pages/game/HamsterCanvas/helpers/circle.ts
> +  y: number
Стоит вынести интерфейс для `Circle` и тогда методы отдельно можно будет не типизировать

2024-06-25 10:19 UTC, kyzinatra commented on packages/client/src/pages/game/HamsterCanvas/helpers/circle.ts
> +    if (context) {
Здорово, что вы выделели классы

2024-06-25 10:21 UTC, kyzinatra commented on packages/client/src/pages/game/HamsterCanvas/index.tsx
> +            circleArray[i].update(
Эту часть тоже лучше вынести в классы. В компонене стоит оставить минимум. Только создание класса-контроллера

2024-06-25 10:21 UTC, kyzinatra commented on packages/client/src/pages/game/HamsterCanvas/index.tsx
> +          const gradient = ctx.createLinearGradient(20, 0, 400, 0)
По аналогии это лучше вынести

2024-06-25 10:22 UTC, kyzinatra commented on packages/client/src/pages/game/HamsterCanvas/index.tsx
> +      )
Вычисление дистанции лучше в отдельную функцию в utils вынести

2024-06-25 10:24 UTC, kyzinatra approved these changes
Отличная работа! Хорошая реализация логики на Canvas. Из моментов, которые можно улучшить замечу, что из компонентов react стоит убрать canvas. То есть должен создаваться контроллер для управления игрой, а вся логика уже должна быть вынесена в классы. Также замечу, что стоит разделить логику игры и ее рендер. То есть сделать такой вот MVC паттерн.

2024-06-25 12:02 UTC, holypower777 submitted a review, later dismissed

2024-06-26 04:45 UTC, alexxxpo approved these changes

2024-06-26 07:44 UTC, holypower777 approved these changes

2024-06-26 07:57 UTC, merged